### ISSUE TITLE
0 becomes a Ø 

### ISSUE THREAD

**Issue by Sgeets** [wa2nfn/morse_code_practice_text#1]
The number '0' becomes 'Ø' (slashed zero) which in morse are different characters .  
'0'  : ----- 
'Ø' : ---.

Is there a way/option to change this behavior ?

**Comment by wa2nfn** [comment]
HelloThe slashed zero is only for visual purposes.  The output to a file is a standard zero. It would only be a problem if you cut and paste from the screen. All this being said I see you email has reference to GitHub I think it’s easy to find the string because it’s in UTF notation so not have it use it is an easy change. Should something like \U000…,Let me know me know your intent I can easily find and change the one source file. 73 Bill=30=On Mar 18, 2023, at 12:31 PM, Sgeets ***@***.***> wrote:﻿
The number '0' becomes 'Ø' (slashed zero) which in morse are different characters .
'0'  : -----
'Ø' : ---.
Is there a way/option to change this behavior ?

**Comment by Sgeets** [comment]
Hey, thanks for your quick answer.   I copy/paste the MCPT output to LCWO to generate some .mp3's.  And you're right,  the '0' got replaced by "\u00D8" a slashed zero.  When written to a file it's ok, which is for now the preferred way. So maybe this could be a future option, to output as is.  Rgds, S
PS: nice tool you made, many options & handy !

**Comment by Sgeets** [comment]
Closing for now.  File output is ok.
