### ISSUE TITLE
<KA> prosign

### ISSUE THREAD

**Issue by Sgeets** [wa2nfn/morse_code_practice_text#2]
When using codeGroups the \<KA> pro sign keeps appearing even when not specified in the cgList option OR when using the prosignFile option (leaving out \<KA> in the file).

I.e. 

 ```
mcpt -codeGroups -cgLen=5:5  -num=40 -cgList="a-z0-9<AS><SK>"

                         MCPT - Morse Code Practice Text
                                     v 2.2
                                    by WA2NFN

I<KA>2WI S2N9P 4X5TR C5FU7 ØVGL<SK> TB5BG OWH4X C1WSA IQK93 YWØVE SA5FW 7GUUC <SK>XPKG ZM3Z<KA>
XNY93 L<KA>OFØ QEY6Y 86J7E 1NGCP IF<AS>AQ L2C<KA><AS> L9EAØ PNJQO VZ<SK>6B 83Q2E <SK>7IZG HMS6U <AS>K1HR
SJU<KA>O THAE8 KFOMR INJJ8 ZHXMR 85<AS>4F 4HCRØ 3Y2<AS>A KVPT1 M49<SK>B 1JVLT B<KA>7B6
```

**Comment by Sgeets** [comment]
At least I found where that \<KA> comes from.  Character d got replaced by a \<KA>.  Why ? 

```
 MCPT> mcpt -codeGroups -inLen=5:5  -num=10 -cgList d

                         MCPT - Morse Code Practice Text
                                     v 2.2
                                    by WA2NFN

<KA><KA><KA><KA><KA> <KA><KA><KA><KA><KA> <KA><KA><KA><KA><KA> <KA><KA><KA><KA><KA> <KA><KA><KA><KA><KA> <KA><KA><KA><KA><KA> <KA><KA><KA><KA><KA> <KA><KA><KA><KA><KA> <KA><KA><KA><KA><KA> <KA><KA><KA><KA><KA>
```

**Comment by wa2nfn** [comment]
well with 50 some supported characters times a dozen supported tutors, you
hit the one allowed lowercase char ;-)

it should have only been allowed for -tutor=FARSAWORTH.

FYI internally I use UC for everything, that allows me to use a few no
supported (IMHO) characters like {[}and d for use as prosigns, then I
reconvert back.

This way I use byte slices for the lists and can use a random number to
select things from lists. This was my first Go program, so I have done a
number of kludgy things. In retrospect, I probably should have relied more
on maps, but I didn't know about them in the early  days.

Glad you found it. BTW I have never gotten any emails from git.

tnx

73 and hope it helps you some how. I don't think there is much of a
following because so many people are GUI only types.

I'll be archiving a Perl IWR (instant word recognition) tool soon. Its a
feature on top of a very complete tool by KY8D for convering entire books
to wav/mp3.

**Comment by wa2nfn** [comment]
Ah now I got them.

BTW src is no 2.2.5

**Comment by Sgeets** [comment]
Compiled & tested.  Thx for fixing ! Closing TT

MCPT> mcpt -codeGroups -inLen=5:5  -num=40 -cgList 0d -zero

                         MCPT - Morse Code Practice Text
                                     v 2.2.5
                                    by WA2NFN

doing zero

D0000 DD000 DD000 0DD00 D0DD0 DD00D DDDDD 0DD00 D0000 D00D0 0DDDD DDD00 000D0 00DDD
0DD00 000D0 D000D DDD0D D0D0D 00D00 0DDD0 D0D00 DDD00 D0000 0000D 0D0D0 D0DDD D0DDD
DDD00 D00D0 000D0 D000D DDD00 0DDDD 0DD00 DD0DD DDDDD 00D0D D00DD 0D0D0
